---
title: "Excercise_5.2_C"
author: "edris safari"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(ggplot2)
library(readxl)
library(plotly)
library(RColorBrewer)
```
## Exercise 2.2.C Charts

Load data

```{r import data1,echo=FALSE,message=FALSE,warning=FALSE}
setwd("D:/GitHub/Safarie1103/Bellevue University/Courses/DSC640/Week9and10")

getwd()



```
```{r Heatmap plots ,echo=FALSE,message=FALSE,warning=FALSE}
ppg2008 <- read.csv('data/ppg2008.csv', sep=",", header=TRUE)
ppg2008 <- ppg2008[order(ppg2008$G,decreasing=FALSE),]
row.names(ppg2008) <-ppg2008$Name
ppg2008 <- ppg2008[,2:20]
ppg2008_matrix<-data.matrix(ppg2008)

bball_heatmap <- heatmap(ppg2008_matrix, Rowv=NA,
    Colv=NA, col = cm.colors(256), scale="column", margins=c(5,10))

bball_heatmap <- heatmap(ppg2008_matrix,
    Rowv=NA, Colv=NA, col = heat.colors(256), scale="column",
    margins=c(5,10))

red_colors <- c("#ffd3cd", "#ffc4bc", "#ffb5ab",
    "#ffa69a", "#ff9789", "#ff8978", "#ff7a67", "#ff6b56",
    "#ff5c45", "#ff4d34")
bball_heatmap <- heatmap(ppg2008_matrix, Rowv=NA,
    Colv=NA, col = red_colors, scale="column", margins=c(5,10))


bball_heatmap <- heatmap(ppg2008_matrix, Rowv=NA,
    Colv=NA, col = brewer.pal(9, "Blues"),
    scale="column", margins=c(5,10))

```
```{r spatial map data1,echo=FALSE,message=FALSE,warning=FALSE}
library(maps)

costcos_geocoded <- read.csv('data/costcos-geocoded.csv', sep=",", header=TRUE)

map(database="state",col="#cccccc")


symbols(costcos_geocoded$Longitude,costcos_geocoded$Latitude,bg="#e2373f", fg="#ffffff",lwd=0.5,circles=rep(1,length(costcos_geocoded$Longitude)),inches=.05,add=TRUE)

map(database="world",col="#cccccc")


symbols(costcos_geocoded$Longitude,costcos_geocoded$Latitude,bg="#e2373f", fg="#ffffff",lwd=0.5,circles=rep(1,length(costcos_geocoded$Longitude)),inches=.05,add=TRUE)





```
```{r Plot3 data1,echo=FALSE,message=FALSE,warning=FALSE}

ppg2008 <- read.csv('data/ppg2008.csv', sep=",", header=TRUE)
ppg2008 <- ppg2008[order(ppg2008$G,decreasing=FALSE),]
row.names(ppg2008) <-ppg2008$Name
ppg2008 <- ppg2008[,2:20]

library(ggplot2)
ggplot(data=ppg2008,aes(x = G,y = PTS)) + 
  xlim(0,100) +
  ylim(0,50) + theme_bw()  + geom_point(alpha=0.1,col="darkblue") +
  geom_density2d(color="black") + ggtitle("Contour Map") + 
  theme(plot.title = element_text(hjust=0.5)) + 
  labs(x = "Games Played",y = "Points Scored")

```
