---
title: "Assignment 3.2.C"
author: "edris safari"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(ggplot2)
library(readxl)
library(plotly)

```
## Exercise 2.2.C Charts

Load data

```{r import data1,echo=FALSE,message=FALSE,warning=FALSE}
setwd("D:/GitHub/Safarie1103/Bellevue University/Courses/DSC640/Week5and6")

getwd()
unemployementRate = read.csv("Data/unemployement-rate-1948-2010.csv")
head(unemployementRate)
```

```{r import data2,echo=FALSE,message=FALSE,warning=FALSE}

getwd()
expenditures = read.table("Data/expenditures.txt",sep="\t",header=TRUE)
head(expenditures)

```
### Treemap Chart
```{r draw Treemap chart ,echo=FALSE,message=FALSE,warning=FALSE}
# basic treemap
treemap(expenditures,
            index=c("category","year"),
            vSize="expenditure",
            type="index",
            palette = "Set2",
            
            align.labels=list(
              c("center", "center"), 
              c("right", "bottom")
            )  
          )           


```
### Area Chart  Chart
```{r draw Area Chart1 ,echo=FALSE,message=FALSE,warning=FALSE}
head(CO2)
data <- CO2 %>% 
  filter(Treatment %in% c("nonchilled")) 
ggplot(data,aes(x=uptake)) + 
  geom_area(stat="bin",bins=20,color="red3",linetype="dashed",fill="yellowgreen") +
  ggtitle("CO2 uptake of all Grass(nonChilled) in Quebec and Mississippi")

```
### Area Chart  Chart
```{r draw Area Chart1 ,echo=FALSE,message=FALSE,warning=FALSE}
head(CO2)
data <- CO2 %>% 
  filter(Type %in% c("Quebec")) %>% 
  filter(Treatment %in% c("nonchilled")) 
ggplot(data,aes(x=uptake)) + 
  geom_area(stat="bin",bins=20,color="red3",linetype="dashed",fill="yellowgreen") +
  ggtitle("CO2 uptake of all Grass(nonChilled) in Quebec")

```
### Stacked Area Chart  Chart
```{r draw stacked Area Chart ,echo=FALSE,message=FALSE,warning=FALSE}

# Libraries
library(tidyverse)
library(babynames)
library(viridis)
library(hrbrthemes)
library(plotly)


# Load babynames dataset
data <- babynames %>% 
  filter(name %in% c("John", "William","Thomas", "Charles", "Henry",  "Robert")) %>%
  filter(sex=="M")

# Plot
p <- data %>% 
  ggplot( aes(x=year, y=n, fill=name, text=name)) +
    geom_area( ) +
    scale_fill_viridis(discrete = TRUE) +
    theme(legend.position="none") +
    ggtitle("Popularity of American names for boys over a 30 year span") +
    theme_ipsum() +
    theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
        ) + 
  labs(x="", y="")


ggplotly(p, tooltip="text")

```
